"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class arm_actions_t(object):

    __slots__ = ["data"]

    __typenames__ = ["float"]

    __dimensions__ = [[6]]

    def __init__(self):
        self.data = [ 0.0 for dim0 in range(6) ]
        """ LCM Type: float[6] """

    def encode(self):
        buf = BytesIO()
        buf.write(arm_actions_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>6f', *self.data[:6]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arm_actions_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arm_actions_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = arm_actions_t()
        self.data = struct.unpack('>6f', buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if arm_actions_t in parents: return 0
        tmphash = (0x5c782a36eaf5245c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if arm_actions_t._packed_fingerprint is None:
            arm_actions_t._packed_fingerprint = struct.pack(">Q", arm_actions_t._get_hash_recursive([]))
        return arm_actions_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", arm_actions_t._get_packed_fingerprint())[0]

